image: quay.io/ssmiller25/gitpod-k8s:20220104-2
tasks:
  - name: Setup Environments
    init: |
      bash $HOME/scripts/cloud-civo.sh
      bash $HOME/scripts/cr-docker.sh
      bash $HOME/scripts/cr-quay.sh
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools