image: quay.io/ssmiller25/gitpod-k8s:20220108-1
tasks:
  - name: Login to Cloud Resources
    command: |
      bash $HOME/scripts/cr-docker.sh
      bash $HOME/scripts/cr-quay.sh
      bash $HOME/scripts/cloud-civo.sh
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools