# https://taskfile.dev

version: '3'

vars:
  version: 20220312-1
  release_date: 
    sh: date +%Y-%m-%d
  upstream_image: gitpod/workspace-full@sha256:42c36a03ed9f1632dce28d4564c376416c77bcd1ea4f2cef509d2ee60d66357b
  image_name: gitpod-k8s
  build_repo: quay.io/ssmiller25
  build_image: '{{.build_repo}}/{{.image_name}}'
  git_hash:
    sh: git rev-parse --short -q HEAD
  run_flags: 

tasks:
  default:
    cmds:
      - echo "{{.version}}"
    silent: true
  docker:latest-sha256:
    cmds:
      - docker pull gitpod/workspace-full:latest      
      - docker inspect --format='{{"{{"}}index .RepoDigests 0{{"}}"}}' gitpod/workspace-full:latest
  docker:build:
    cmds:
      - |
        docker build . -t {{.build_image}}:{{.git_hash}} \
        --build-arg GIT_HASH={{.git_hash}} \
        --build-arg VERSION={{.version}} \
        --build-arg RELEASE_DATE={{.release_date}} \
        --build-arg UPSTREAM_IMAGE={{.upstream_image}}
  docker:run:
    cmds:
      - task: docker:stop
      - docker run --rm {{.run_flags}} -it --name {{.image_name}} {{.build_image}}:{{.git_hash}}

  docker:stop:
    cmds:
      - docker stop {{.image_name}} > /dev/null 2>&1 || true

  docker:push:
    cmds:
      - docker tag {{.build_image}}:{{.git_hash}} {{.build_image}}:{{.version}}
      - docker tag {{.build_image}}:{{.git_hash}} {{.build_image}}:latest
      - docker push {{.build_image}}:{{.git_hash}}
      - docker push {{.build_image}}:{{.version}}
      - docker push {{.build_image}}:latest
